/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Erin
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
    }
    
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanelMainComands = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        btnVerEstado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnLogApp = new javax.swing.JButton();
        btnCrearApp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCrearImpresora = new javax.swing.JButton();
        btnLogPrint = new javax.swing.JButton();
        btnCMD = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuExit = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menIrInicio = new javax.swing.JMenuItem();
        menIrCrearApp = new javax.swing.JMenuItem();
        menIrCrearImpre = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spooler");
        setMaximumSize(new java.awt.Dimension(550, 550));
        setMinimumSize(new java.awt.Dimension(550, 550));
        setPreferredSize(new java.awt.Dimension(550, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(550, 550));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel1.setText("Spooler");

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnVerEstado.setText("Ver estado");
        btnVerEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstadoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Aplicaciones"));

        btnLogApp.setText("Historial ");
        btnLogApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogAppActionPerformed(evt);
            }
        });

        btnCrearApp.setText("Crear Aplicación");
        btnCrearApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogApp)
                    .addComponent(btnCrearApp))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrearApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogApp)
                .addGap(33, 33, 33))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Impresoras")));

        btnCrearImpresora.setText("Crear Impresora");
        btnCrearImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearImpresoraActionPerformed(evt);
            }
        });

        btnLogPrint.setText("Historial");
        btnLogPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearImpresora)
                    .addComponent(btnLogPrint))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(btnCrearImpresora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogPrint)
                .addGap(16, 16, 16))
        );

        btnCMD.setText("CMD");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pr.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMainComandsLayout = new javax.swing.GroupLayout(jPanelMainComands);
        jPanelMainComands.setLayout(jPanelMainComandsLayout);
        jPanelMainComandsLayout.setHorizontalGroup(
            jPanelMainComandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainComandsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainComandsLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(jPanelMainComandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainComandsLayout.createSequentialGroup()
                        .addComponent(btnCMD)
                        .addGap(37, 37, 37)
                        .addComponent(btnImprimir)
                        .addGap(36, 36, 36)
                        .addComponent(btnVerEstado))
                    .addGroup(jPanelMainComandsLayout.createSequentialGroup()
                        .addGroup(jPanelMainComandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)))
                .addGap(46, 46, 46))
        );
        jPanelMainComandsLayout.setVerticalGroup(
            jPanelMainComandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainComandsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelMainComandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelMainComandsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanelMainComandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCMD)
                    .addComponent(btnImprimir)
                    .addComponent(btnVerEstado))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jMenuExit.setText("File");

        jMenuItem2.setText("Ayuda");
        jMenuExit.add(jMenuItem2);

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuExit.add(jMenuItem1);

        jMenuBar1.add(jMenuExit);

        jMenu3.setText("Ir");

        menIrInicio.setText("Inicio");
        menIrInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIrInicioActionPerformed(evt);
            }
        });
        jMenu3.add(menIrInicio);

        menIrCrearApp.setText("Crear aplicación");
        menIrCrearApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIrCrearAppActionPerformed(evt);
            }
        });
        jMenu3.add(menIrCrearApp);

        menIrCrearImpre.setText("Crear impresora");
        menIrCrearImpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIrCrearImpreActionPerformed(evt);
            }
        });
        jMenu3.add(menIrCrearImpre);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMainComands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanelMainComands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void createApp(){
        
        createApp ventCreateApp = new createApp();
        ventCreateApp.setVisible(true);
        this.dispose();
    }
    
    private void btnCrearAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAppActionPerformed
        // TODO add your handling code here:
        createApp();
    }//GEN-LAST:event_btnCrearAppActionPerformed

    protected void createPrinter(){
        
        createPrinter ventCreatePrinter = new createPrinter();
        ventCreatePrinter.setVisible(true);
        this.dispose();

    }
    private void btnCrearImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearImpresoraActionPerformed
        // TODO add your handling code here:
        createPrinter();
    }//GEN-LAST:event_btnCrearImpresoraActionPerformed
    private void logApp(){
        
        LogApp ventLogApp = new LogApp();
        ventLogApp.setVisible(true);
        this.dispose();

    }
    private void btnLogAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogAppActionPerformed
        // TODO add your handling code here:
        logApp();
    }//GEN-LAST:event_btnLogAppActionPerformed

    private void logPrinter(){
        
        LogPrinter ventLogPrinter = new LogPrinter();
        ventLogPrinter.setVisible(true);
        this.dispose();

    }
    
    private void btnLogPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogPrintActionPerformed
        // TODO add your handling code here:
        logPrinter();
    }//GEN-LAST:event_btnLogPrintActionPerformed

    private void menIrInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIrInicioActionPerformed
        // TODO add your handling code here:
        Inicio ventInicio = new Inicio();
        ventInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menIrInicioActionPerformed

    private void menIrCrearAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIrCrearAppActionPerformed
        // TODO add your handling code here:
        createApp();
    }//GEN-LAST:event_menIrCrearAppActionPerformed

    private void menIrCrearImpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIrCrearImpreActionPerformed
        // TODO add your handling code here:
        createPrinter();
    }//GEN-LAST:event_menIrCrearImpreActionPerformed

    private void btnVerEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstadoActionPerformed
        // TODO add your handling code here:
        spooler.accessFrames.verEstado();
        this.dispose();
    }//GEN-LAST:event_btnVerEstadoActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        spooler.accessFrames.imprimir();
        this.dispose();
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCMD;
    private javax.swing.JButton btnCrearApp;
    private javax.swing.JButton btnCrearImpresora;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLogApp;
    private javax.swing.JButton btnLogPrint;
    private javax.swing.JButton btnVerEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMainComands;
    private javax.swing.JMenuItem menIrCrearApp;
    private javax.swing.JMenuItem menIrCrearImpre;
    private javax.swing.JMenuItem menIrInicio;
    // End of variables declaration//GEN-END:variables
}
